GCC 7.4.0
FFTW 3.3.7
GSL 2.4
Anaconda3 5.1.0
Traceback (most recent call last):
  File "/hpc/group/cosmology/denniswu/thre_image_NN.py", line 42, in <module>
    with open('ra_rand_gal.csv', newline='') as rafile:
FileNotFoundError: [Errno 2] No such file or directory: 'ra_rand_gal.csv'
